- name: Install MetalLB
  tags: metallb
  shell: |
    kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/{{ metallb_version }}/config/manifests/metallb-native.yaml
  when: inventory_hostname == groups['master'][0]

- name: Configure MetalLB
  tags: metallb
  shell: |
    cat << 'EOF' | kubectl apply -f -
    apiVersion: metallb.io/v1beta1
    kind: IPAddressPool
    metadata: 
      name: metallb-pool
      namespace: metallb-system
    spec:
      addresses:
        - "{{ metallb_ip_range }}"
    ---
    apiVersion: metallb.io/v1beta1
    kind: L2Advertisement
    metadata:
      name: config
      namespace: metallb-system
    spec:
      ipAddressPools:
        - metallb-pool
  when: inventory_hostname == groups['master'][0]