---

- name: Update apt repo and cache
  apt:
    update_cache: true
    force_apt_get: true
    cache_valid_time: 3600 

- name: Upgrade all packages on servers
  apt: 
    upgrade: dist
    force_apt_get: true

- name: Install prerequisites apps
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - net-tools
      - vim
      - curl
    state: present
    update_cache: true